server:
  port: 10001
spring:
  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/hello?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    minIdle: 1
    testOnBorrow: false
    loginUsername: vap
    loginPassword: vap
  jpa:
    generate-ddl: false # 自动创建表结构
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:192.168.120.234}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:vrv@1234}
    timeout: 5000  # 连接超时时间（毫秒）
    database: 1
vap:
  cache:
    configs:
      - key: menu
        second: 300
      - key: qax
        second: 3600

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
    com.vrv.vap: INFO
    root: WARN
    org.hibernate.type: TRACE
