server:
  port: 10000
spring:
  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/hello?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    minIdle: 1
    testOnBorrow: false
    loginUsername: vap
    loginPassword: vap
  jpa:
    generate-ddl: false # 自动创建表结构
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
    com.vrv.vap: INFO
    root: WARN
    org.hibernate.type: TRACE
